// Emojis
export const EMOJIS = {
  MONEY: '💰',
  GAME: '🎮',
  TROPHY: '🏆',
  FIRE: '🔥',
  CHART: '📊',
  DEPOSIT: '💳',
  WITHDRAW: '💸',
  PROFILE: '👤',
  RANKING: '🏅',
  HISTORY: '📋',
  RULES: '📖',
  SUPPORT: '🆘',
  SUCCESS: '✅',
  ERROR: '❌',
  WARNING: '⚠️',
  INFO: 'ℹ️',
  WAITING: '⏳',
  PLAY: '▶️',
  PAUSE: '⏸️',
  STOP: '⏹️',
  COIN: '🪙',
  DICE: '🎲',
  ROCK: '🪨',
  PAPER: '📄',
  SCISSORS: '✂️',
  DOMINO: '🀄',
  HEADS: '😎',
  TAILS: '👑',
  WALLET: '💼',
  HELP: '❓',
  BACK: '⬅️',
  BALANCE: '💰',
  STATS: '📊',
  USERS: '👥',
  COINS: '🪙',
  GAMES: '🎯',
  SETTINGS: '⚙️',
  QUESTION: '❓',
  CUSTOM: '✏️',
  CHECK: '✅',
  CROSS: '❌',
  INACTIVE: '🚫',
  EXIT: '🚪',
} as const;

export const GAME_TYPES = {
  COIN_FLIP: 'coin_flip',
  ROCK_PAPER_SCISSORS: 'rock_paper_scissors',
  DICE: 'dice',
  TOURNAMENT: 'tournament',
  DOMINO: 'domino',
} as const;
